# Generated by Django 5.2.13 on 2026-05-13 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HouseholdInformationTable',
            fields=[
                ('Household_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Postal_code', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightingFeeTable',
            fields=[
                ('Lamp_Type_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Lamp_Type', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LightingPaymentTable',
            fields=[
                ('Payment_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Payment_Time', models.DateTimeField(auto_now_add=True, verbose_name='繳費時間')),
                ('GuangMing_Count', models.IntegerField(default=0, verbose_name='光明燈數量')),
                ('TaiSui_Count', models.IntegerField(default=0, verbose_name='太歲燈數量')),
                ('Total_Amount', models.IntegerField(default=0, verbose_name='總金額')),
                ('Household_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light.householdinformationtable', verbose_name='所屬住戶')),
            ],
            options={
                'db_table': 'lighting_payment_table',
            },
        ),
        migrations.CreateModel(
            name='MemberInformationTable',
            fields=[
                ('Member_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Lunar_Birthday', models.DateField(blank=True, null=True)),
                ('Gregorian_Birthday', models.DateField(blank=True, null=True)),
                ('Profile_Creation_Time', models.DateTimeField(auto_now_add=True)),
                ('Profile_Update_Time', models.DateTimeField(auto_now=True)),
                ('Household_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light.householdinformationtable')),
            ],
        ),
        migrations.AddField(
            model_name='householdinformationtable',
            name='Head_of_Household_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='light.memberinformationtable'),
        ),
        migrations.CreateModel(
            name='LightingRecordTable',
            fields=[
                ('Lighting_Record_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Lamp_Lighting_Date', models.DateField()),
                ('Record_Creation_Time', models.DateTimeField(auto_now_add=True)),
                ('Record_Updated_Time', models.DateTimeField(auto_now=True)),
                ('print_status', models.CharField(choices=[('not_printed', 'Not Printed'), ('printed', 'Printed')], default='not_printed', max_length=20)),
                ('Household_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light.householdinformationtable')),
                ('Lamp_Type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light.lightingfeetable')),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light.memberinformationtable')),
            ],
            options={
                'unique_together': {('Member_ID', 'Lamp_Type_ID', 'Year')},
            },
        ),
    ]
