# Generated by Django 5.2.13 on 2026-05-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingrecordtable',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='是否已繳費'),
        ),
        migrations.AddField(
            model_name='lightingrecordtable',
            name='payment_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='light.lightingpaymenttable', verbose_name='關聯繳費紀錄'),
        ),
    ]
