# Generated by Django 5.2.13 on 2026-05-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0002_lightingrecordtable_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingpaymenttable',
            name='Household_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light.householdinformationtable', verbose_name='所屬住戶'),
        ),
    ]
