# Generated by Django 6.0.3 on 2026-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("light", "0003_alter_lightingpaymenttable_household_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lightingrecordtable",
            name="Amount",
            field=models.IntegerField(default=0, verbose_name="點燈金額"),
        ),
        migrations.AddField(
            model_name="lightingrecordtable",
            name="Notes",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="備註"
            ),
        ),
    ]
