# Generated by Django 6.0.3 on 2026-05-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("believer", "0004_household_information_mobile"),
        ("light", "0004_lightingrecordtable_amount_lightingrecordtable_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lightingrecordtable",
            name="Household_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="believer.household_information",
            ),
        ),
        migrations.RemoveField(
            model_name="memberinformationtable",
            name="Household_ID",
        ),
        migrations.AlterField(
            model_name="lightingpaymenttable",
            name="Household_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="believer.household_information",
                verbose_name="所屬住戶",
            ),
        ),
        migrations.AlterField(
            model_name="lightingrecordtable",
            name="Member_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="believer.member_information",
            ),
        ),
        migrations.DeleteModel(
            name="HouseholdInformationTable",
        ),
        migrations.DeleteModel(
            name="MemberInformationTable",
        ),
    ]
