# Generated by Django 6.0.3 on 2026-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household_Information",
            fields=[
                (
                    "Household_ID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "Head_of_Household_ID",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Postal_code", models.IntegerField()),
                ("Address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Household_Information_Table",
            },
        ),
        migrations.CreateModel(
            name="Member_Information",
            fields=[
                (
                    "Member_ID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("Household_ID", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("Lunar_Birthday", models.DateField()),
                ("Gregorian_Birthday", models.DateField()),
                ("isHeadOfHousehold", models.BooleanField(default=False)),
                ("Profile_Creation_Time", models.DateTimeField(auto_now_add=True)),
                ("Profile_Update_Time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Member_Information_Table",
            },
        ),
    ]
