# Generated by Django 6.0.3 on 2026-05-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("believer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member_information",
            name="Household_ID",
        ),
        migrations.AddField(
            model_name="member_information",
            name="Household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="believer.household_information",
            ),
        ),
    ]
