# Generated by Django 6.0.3 on 2026-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("believer", "0003_backfill_household_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="household_information",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
