# Generated by Django 6.0.3 on 2026-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation_Record",
            fields=[
                ("Donation_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Member_ID", models.CharField(blank=True, max_length=100, null=True)),
                ("Believer_Name", models.CharField(max_length=100)),
                ("Gregorian_Birthday", models.DateField()),
                (
                    "Donation_Amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("Donation_Date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Donation_Record_Table",
            },
        ),
    ]
