# Generated by Django 5.2.13 on 2026-05-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdInformationTable',
            fields=[
                ('Household_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Postal_code', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightingFeeTable',
            fields=[
                ('Lamp_Type_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Lamp_Type', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('系統開發者', '系統開發者'), ('寺廟管理員', '寺廟管理員'), ('志工', '志工')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('Account_Status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('locked', 'Locked'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('Account_Creation_Time', models.DateTimeField(auto_now_add=True)),
                ('Account_Update_Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInformationTable',
            fields=[
                ('Member_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Lunar_Birthday', models.DateField(blank=True, null=True)),
                ('Gregorian_Birthday', models.DateField(blank=True, null=True)),
                ('Profile_Creation_Time', models.DateTimeField(auto_now_add=True)),
                ('Profile_Update_Time', models.DateTimeField(auto_now=True)),
                ('Household_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.householdinformationtable')),
            ],
        ),
        migrations.AddField(
            model_name='householdinformationtable',
            name='Head_of_Household_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.memberinformationtable'),
        ),
        migrations.CreateModel(
            name='LightingRecordTable',
            fields=[
                ('Lighting_Record_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Lamp_Lighting_Date', models.DateField()),
                ('Record_Creation_Time', models.DateTimeField(auto_now_add=True)),
                ('Record_Updated_Time', models.DateTimeField(auto_now=True)),
                ('print_status', models.CharField(choices=[('not_printed', 'Not Printed'), ('printed', 'Printed')], default='not_printed', max_length=20)),
                ('Household_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.householdinformationtable')),
                ('Lamp_Type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.lightingfeetable')),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.memberinformationtable')),
            ],
            options={
                'unique_together': {('Member_ID', 'Lamp_Type_ID', 'Year')},
            },
        ),
    ]
