# Generated by Django 6.0.3 on 2026-04-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128, unique=True)),
                ('Account_Status', models.CharField(max_length=50)),
                ('Account_Creation_Time', models.DateTimeField(auto_now_add=True)),
                ('Account_Update_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User_Account',
            },
        ),
    ]
