# Generated by Django 6.0.3 on 2026-05-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='Account_Status',
            field=models.CharField(choices=[('Active', '啟用'), ('Inactive', '停用'), ('Suspended', '停權')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='role',
            field=models.CharField(choices=[('Admin', '寺廟管理員'), ('Volunteer', '志工')], default='Volunteer', max_length=50),
        ),
    ]
