/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressCascader: typeof import('./components/member/AddressCascader.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExcelPreview: typeof import('./components/common/ExcelPreview.vue')['default']
    HomepageCard: typeof import('./components/common/HomepageCard.vue')['default']
    HouseholdForm: typeof import('./components/member/HouseholdForm.vue')['default']
    HouseholdLampInfoCard: typeof import('./components/lamp/HouseholdLampInfoCard.vue')['default']
    HouseholdTable: typeof import('./components/member/HouseholdTable.vue')['default']
    InlineDateRangePicker: typeof import('./components/common/InlineDateRangePicker.vue')['default']
    LampEditForm: typeof import('./components/lamp/LampEditForm.vue')['default']
    LampHistoryDialog: typeof import('./components/lamp/LampHistoryDialog.vue')['default']
    LampRecordTable: typeof import('./components/lamp/LampRecordTable.vue')['default']
    LampSearchForm: typeof import('./components/lamp/LampSearchForm.vue')['default']
    LunarDatePicker: typeof import('./components/common/LunarDatePicker.vue')['default']
    MemberCard: typeof import('./components/member/MemberCard.vue')['default']
    MemberCardList: typeof import('./components/member/MemberCardList.vue')['default']
    MemberSearchForm: typeof import('./components/member/MemberSearchForm.vue')['default']
    PageTitleBar: typeof import('./components/layout/PageTitleBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
